import MenuButton from "@/components/MenuButton";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { ToggleProvider } from "@/contextProviders/ToggleProvider";
import Sidebar from "@/components/Sidebar";
import MainContent from "@/components/MainContent";

interface Props {
  children: React.ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Props) => {
  const className = inter.className;

  return (
    <html lang="en">
      <body className={inter.className}>
        <ToggleProvider>
          <div className="flex flex-col min-h-screen">
            <nav className="bg-gray-800">
              <div className="max-w-7xl mx-auto px-2 sm:px-4">
                <div className="flex items-center justify-between h-[8vh]">
                  {/* Mobile menu button*/}
                  <MenuButton />

                  {/* Logo */}
                  <div className="flex-shrink-0 flex items-center">
                    <Link href="/" className="text-white font-bold text-2xl">
                      <div className="hidden sm:block">
                        Training And Placement Cell (IITI)
                      </div>
                      <div className="block sm:hidden">TPC</div>
                    </Link>
                  </div>
                  {/* Links */}
                  <div className="ml-2 sm:ml-6">
                    <div className="flex space-x-4">
                      <button className="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-gray-700 transition-all duration-300">
                        <div className="hidden sm:block">Logout</div>
                        <div className="block sm:hidden">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                            fill="#fff"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          >
                            <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                            <polyline points="16 17 21 12 16 7"></polyline>
                            <line x1="21" y1="12" x2="9" y2="12"></line>
                          </svg>
                        </div>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </nav>
            {/* Page Content */}
            <div className="flex flex-grow inherit">
              {/* sidebar and main content share this space */}
              <Sidebar />
              <MainContent>{children}</MainContent>
            </div>
          </div>
        </ToggleProvider>
      </body>
    </html>
  );
};

export default RootLayout;
