name: Push To Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy on remote
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DC_HOST }}
          username: ${{ secrets.DC_USER }}
          password: ${{ secrets.DC_PASS }}
          script: |
            cd ~/camc_portal/camc-frontend
            git pull origin main
            docker stop camc_portal-frontend-1
            docker rm camc_portal-frontend-1
            docker rmi camc_portal-frontend || true
            cd ..
            docker compose up -d
